apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tan-dara5304-spring-maven-17-ingress
  namespace: tan-dara5304-spring-maven-17
  annotation:
spec:
  ingressClassName: nginx
  rules:
  - host: dara.darasr.online
    http:
      paths:
      - path: /
        pathType: Prefix  
        backend:
          service:
            name: tan-dara5304-spring-maven-17-service 
            port:
              number: 8320
