 apiVersion: networking.k8s.io/v1
 kind: Ingress
 metadata:
   name: tan-dara5304-spring-maven-17-https-ingress
   namespace: tan-dara5304-spring-maven-17
   annotations:
     nginx.ingress.kubernetes.io/ssl-redirect: "false"
     nginx.ingress.kubernetes.io/use-regex: "true"
     nginx.ingress.kubernetes.io/proxy-body-size: "5g"    
     nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
     nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
     nginx.ingress.kubernetes.io/rewrite-target: /
 spec:
   ingressClassName: nginx
   tls:
     - hosts:
         - tan-dara5304-spring-maven-17.assessify.org
       secretName: tan-dara5304-spring-maven-17-secret-tls
   rules:
     - host: tan-dara5304-spring-maven-17.assessify.org
       http:
         paths:
           - path: /
             pathType: Prefix
             backend:
               service:
                 name: tan-dara5304-spring-maven-17-service
                 port:
                   number: 8320
 